# Generated by Django 3.2.15 on 2023-09-01 04:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBTCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='4111111111111111', max_length=19, validators=[api.models.validateEBTNumber])),
                ('last_4', models.CharField(max_length=4)),
                ('issue_state', models.CharField(max_length=20)),
                ('brand', models.CharField(choices=[('amex', 'Amex'), ('discover', 'Discover'), ('mastercard', 'Mastercard'), ('visa', 'Visa')], max_length=255)),
                ('issue_month', models.PositiveSmallIntegerField(validators=[api.models.validateMonth])),
                ('issue_year', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
