# Generated by Django 3.2.15 on 2023-09-01 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ebtcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.creditcard'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ebt_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ebtcard'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'credit_card'), ('ebt_card', 'ebt_card')], max_length=25),
        ),
    ]
